import type { Metadata } from 'next';
import './globals.css';
import clsx from 'clsx';
import { suitFont } from '@/libs/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(suitFont.className, 'w-screen h-dvh')}>
        <main className="w-full max-w-[500px] h-full mx-auto ">{children}</main>
        <div id="modal-root" />
      </body>
    </html>
  );
}
